insert into sauce(brand, title, price, description, img_path, ingredients) values ('Crystal', 'Crystal Hot Sauce (The OG)', 8.45, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/crystal-OG.png', 'pepper, vinager, onions'), 
('Marie Sharp', 'Marie Sharp OG Hot', 12.45, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/marie-oghot.png', 'Select red habanero pepper, vinegar, fresh carrots, salt, onions, lime juice and garlic.'), 
('Tabasco', 'Tabasco Red Pepper', 10.25, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/tobasco-redpepper.png', 'pepper, vinager, onions'), 
('Crystal', 'Crystal Hot Sauce Garlic', 7.35, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/crystal-garlic.png', 'Aged red cayenne peppers, distilled vinegar, salt, garlic powder, and natural flavor.'), 
('Marie Sharp', 'Marie Sharp Habanero', 8, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/marie-habanero.png', 'Habanero pepper mash, capsium oil, fresh carrots, ginseng, lime juice, creole spices, onions, garlic and salt.'), 
('Tabasco', 'Tabasco Habanero Pepper', 11.25, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/tabasco-habanero.png', 'pepper, vinager, onions'), 
('Crystal', 'Crystal Extra Hot Sauce', 10.35, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/crystal-extra.png', 'Aged red cayenne peppers, distilled vinegar, water, salt, natural flavorings, xanthan gum.'), 
('Marie Sharp', 'Marie Sharp Pulp Habanero', 11.45, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/marie-pulp.png', 'Select yellow habanero peppers, orange pulp, onions, key lime juice, vinegar, garlic and salt.'), 
('Tabasco', 'Tabasco Green Pepper', 8.25, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/tobasco-green.png', 'pepper, vinager, onions'), 
('Crystal', 'Crystal Buffalo Sauce', 10.35, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/crystal-buffalo.png', 'Distilled vinegar, aged red cayenne peppers, salt, water, canola oil, paprika, garlic powder, xanthan gum, sodium benzoate (preservative), natural butter flavoring.'), 
('Marie Sharp', 'Marie Sharp Smoked Habanero', 14.45, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/smoked.png', 'Smoked habanero pepper, fresh carrots, vinegar, onions, salt, lime juice and garlic.'), 
('Tabasco', 'Tabasco Scorpion', 19.25, ' Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi inventore iure ipsam, ut sed aliquid suscipit reprehenderit aspernatur dolores nulla fuga eaque recusandae nihil aliquam magnam provident laboriosam optio doloribus.','images/tabasco-scorpion.png', 'pepper, vinager, onions'); 


 insert into promocodes(code, value, is_used) values ('AQvillTw7e', 5.00, 0) ,
('ddMHaqylao', 5.00, 0) ,
('pqs6ZFcR8r', 5.00, 0) ,
('sBt6YGbbi3', 5.00, 0) ,
('pRkxhga1pt', 5.00, 0) ,
('7fv6CjVvWb', 5.00, 0) ,
('4bG4iUWVVO', 5.00, 0) ,
('vyTr9Unogg', 5.00, 0) ,
('GYLw1tizYk', 5.00, 0) ,
('0M7ohvhDFZ', 5.00, 0) ;
